"""phase 4 add ticket checkin and resolution

Revision ID: 558ae9bdc4b1
Revises: c931a060d67b
Create Date: 2026-04-07 15:24:56.246356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '558ae9bdc4b1'
down_revision: Union[str, Sequence[str], None] = 'c931a060d67b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_checkin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('technician_user_id', sa.String(length=36), nullable=False),
    sa.Column('photo_public_id', sa.String(length=255), nullable=False),
    sa.Column('photo_secure_url', sa.Text(), nullable=False),
    sa.Column('photo_resource_type', sa.String(length=50), nullable=False),
    sa.Column('photo_format', sa.String(length=50), nullable=True),
    sa.Column('photo_bytes', sa.Integer(), nullable=False),
    sa.Column('photo_width', sa.Integer(), nullable=True),
    sa.Column('photo_height', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technician_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'technician_user_id', name='uq_ticket_checkin_ticket_technician')
    )
    op.create_index(op.f('ix_ticket_checkin_id'), 'ticket_checkin', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_checkin_technician_user_id'), 'ticket_checkin', ['technician_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_checkin_ticket_id'), 'ticket_checkin', ['ticket_id'], unique=False)
    op.create_table('ticket_resolution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('technician_user_id', sa.String(length=36), nullable=False),
    sa.Column('video_public_id', sa.String(length=255), nullable=False),
    sa.Column('video_secure_url', sa.Text(), nullable=False),
    sa.Column('video_resource_type', sa.String(length=50), nullable=False),
    sa.Column('video_format', sa.String(length=50), nullable=True),
    sa.Column('video_bytes', sa.Integer(), nullable=False),
    sa.Column('video_width', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('video_duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technician_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'technician_user_id', name='uq_ticket_resolution_ticket_technician')
    )
    op.create_index(op.f('ix_ticket_resolution_id'), 'ticket_resolution', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_resolution_technician_user_id'), 'ticket_resolution', ['technician_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_resolution_ticket_id'), 'ticket_resolution', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_resolution_ticket_id'), table_name='ticket_resolution')
    op.drop_index(op.f('ix_ticket_resolution_technician_user_id'), table_name='ticket_resolution')
    op.drop_index(op.f('ix_ticket_resolution_id'), table_name='ticket_resolution')
    op.drop_table('ticket_resolution')
    op.drop_index(op.f('ix_ticket_checkin_ticket_id'), table_name='ticket_checkin')
    op.drop_index(op.f('ix_ticket_checkin_technician_user_id'), table_name='ticket_checkin')
    op.drop_index(op.f('ix_ticket_checkin_id'), table_name='ticket_checkin')
    op.drop_table('ticket_checkin')
    # ### end Alembic commands ###
