"""phase 3 add ticket response field

Revision ID: c931a060d67b
Revises: 3f3d8e3f7d44
Create Date: 2026-04-06 11:28:49.276273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c931a060d67b'
down_revision: Union[str, Sequence[str], None] = '3f3d8e3f7d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('intial_respons', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('responded_by_user_id', sa.String(length=36), nullable=True))
    op.add_column('tickets', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['responded_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'responded_at')
    op.drop_column('tickets', 'responded_by_user_id')
    op.drop_column('tickets', 'intial_respons')
    # ### end Alembic commands ###
